services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # - type: bind
      #   source: ./
      #   target: /
      - type: bind
        source: ./portfolio.csv
        target: /portfolio.csv
      - type: bind
        source: ./PaperStudy.csv
        target: /PaperStudy.csv
      - type: bind
        source: ./DOW100.csv
        target: /DOW100.csv
      - type: bind
        source: ./Nasdaq100.csv
        target: /Nasdaq100.csv
      - type: bind
        source: ./SP100.csv
        target: /SP100.csv
    networks:
      - stock-picker-network
    #    depends_on:
    #      - ib-gateway
    environment:
      - PORT=8080
      - IB_GATEWAY_HOST=ib-gateway
      - IB_GATEWAY_PORT=4002
      - IB_USERNAME=${IB_USERNAME:-username}
      - IB_PASSWORD=${IB_PASSWORD:-password}
    restart: always

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    #      - ib-gateway
    restart: always
    networks:
      - stock-picker-network

#  ib-gateway:
#    restart: always
#    container_name: ib-container
#    hostname: ib-gateway
#    build:
#      context: ./ib-gateway
#      dockerfile: Dockerfile
#    environment:
#      TWS_USERID: ${IB_USERNAME:-username}
#      TWS_PASSWORD: ${IB_PASSWORD:-password}
#      TRADING_MODE: ${TRADING_MODE:-paper}
#      READ_ONLY_API: ${READ_ONLY:-no}
#      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-password}
#    ports:
#      - "127.0.0.1:4001:4001"
#      - "127.0.0.1:4002:4002"
#      - "127.0.0.1:5900:5900"
#    networks:
#      - stock-picker-network

networks:
  stock-picker-network:
    driver: bridge
